// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.25.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

Future<BMPimage> renderImage(
        {required int width, required int height, dynamic hint}) =>
    RustLib.instance.api.renderImage(width: width, height: height, hint: hint);

class BMPimage {
  final int width;
  final int height;
  final Uint8List bmp;

  const BMPimage({
    required this.width,
    required this.height,
    required this.bmp,
  });

  static Future<BMPimage> newBMPimage(
          {required int width,
          required int height,
          required List<int> pixels,
          dynamic hint}) =>
      RustLib.instance.api.bmPimageNew(
          width: width, height: height, pixels: pixels, hint: hint);

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ bmp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BMPimage &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          bmp == other.bmp;
}
